\c project4;
CREATE TABLE crimes (
    id integer PRIMARY KEY,
    case_number varchar,
    date date,
    block varchar,
    iucr varchar,
    primary_type varchar,
    description varchar,
    location_description varchar,
    arrest boolean,
    domestic boolean,
    beat ineger,
    district integer,
    ward integer,
    community_area integer,
    fbi_code varchar,
    x_coordinate integer,
    y_coordinate integer,
    year integer,
    updated_on date,
    latitude numeric,
    longitude numeric,
    location varchar,
    :@computed_region_awaf_s7ux integer,
    :@computed_region_6mkv_f3dw integer,
    :@computed_region_vrxf_vc4k integer,
    :@computed_region_bdys_3d7i integer,
    :@computed_region_43wa_7qmu integer,
    :@computed_region_rpca_8um6 integer,
    :@computed_region_d9mm_jgwp integer,
    :@computed_region_d3ds_rm58 integer
;
\copy  crime (id, case_number, date, block, iucr, primary_type, description, location_description, arrest, domestic, beat, district, ward, community_area, fbi_code, x_coordinate, y_coordinate, year, updated_on, latitude, longitude, location, :@computed_region_awaf_s7ux, :@computed_region_6mkv_f3dw, :@computed_region_vrxf_vc4k, :@computed_region_bdys_3d7i, :@computed_region_43wa_7qmu, :@computed_region_rpca_8um6, :@computed_region_d9mm_jgwp, :@computed_region_d3ds_rm58) FROM 'C:\Users\HyeOL\CUNY\GitHub\project_4\data\crime.csv' WITH (FORMAT csv, HEADER);
CREATE TABLE clinics (
    id integer PRIMARY KEY,
    organization varchar,
    site_name varchar,
    site_type varchar,
    address varchar,
    zip varchar,
    main_phone varchar,
    service_request_phone varchar,
    evening_hours_availability boolearn,
    evening_hours_detail varchar,
    weekend_hours_availability boolearn,
    ticc_site varchar,
    all_community_areas_served varchar,
    wards_served varchar,
    police_districts_served varchar,
    accepts_uninsured_patients boolean,
    sliding_scale_fees boolean,
    insurance_accepted varchar,
    age_range_served varchar,
    primary_care_availability boolean,
    bhs_service_availability_primary_care varchar,
    telehealth_services_availability boolean,
    other_languages varchar,
    language_line_availability boolean,
    behavioral_services_types varchar,
    crisis_services boolean,
    mental_health_services_type_special_needs_availability varchar,
    school_based_services_availability boolean,
    grief_services_availability boolean,
    first_episode_psychosis_programming_availability boolean,
    substance_use_services_availability boolean,
    location varchar,
    :@computed_region_rpca_8um6 integer,
    :@computed_region_vrxf_vc4k integer,
    :@computed_region_6mkv_f3dw integer,
    :@computed_region_bdys_3d7i integer,
    :@computed_region_43wa_7qmu integer,
    weekend_hours_detail varchar,
    grief_bereavement_services_types varchar,
    substance_use_services_type varchar,
    mar_medications_opioid varchar,
    harm_reduction_services varchar,
    service_request_alternative_availability boolean,
    service_request_alternative_detail varchar,
    hours varchar,
    mental_health_services_type_special_needs_detail varchar,
    ticc_areas_served varchar,
    mar_medications_alcohol varchar,
    crisis_intake_phone varchar,
    crisis_services_hours varchar,
    crisis_services_types varchar,
    first_episode_psychosis_programming_detail varchar
;
\copy  clinics (organization, site_name, site_type, address, zip, main_phone, service_request_phone, evening_hours_availability, evening_hours_detail, weekend_hours_availability, ticc_site, all_community_areas_served, wards_served, police_districts_served, accepts_uninsured_patients, sliding_scale_fees, insurance_accepted, age_range_served primary_care_availability, bhs_service_availability_primary_care, telehealth_services_availability, other_languages, language_line_availability, behavioral_services_types, crisis_services, mental_health_services_type_special_needs_availability, school_based_services_availability, grief_services_availability, first_episode_psychosis_programming_availability, substance_use_services_availability, location, :@computed_region_rpca_8um6, :@computed_region_vrxf_vc4k, :@computed_region_6mkv_f3dw, :@computed_region_bdys_3d7i, :@computed_region_43wa_7qmu, weekend_hours_detail, grief_bereavement_services_types, substance_use_services_type, mar_medications_opioid, harm_reduction_services, service_request_alternative_availability, service_request_alternative_detail, hours, mental_health_services_type_special_needs_detail, ticc_areas_served, mar_medications_alcohol, crisis_intake_phone, crisis_services_hours, crisis_services_types, first_episode_psychosis_programming_detail
) FROM 'C:\Users\HyeOL\CUNY\GitHub\project_4\data\clinics.csv' WITH (FORMAT csv, HEADER);